# Generated by Django 5.2.5 on 2025-12-10 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_coursemoduleitem_test_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_obtained', models.FloatField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('student_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.test')),
            ],
        ),
    ]
