# Generated by Django 5.2.5 on 2025-12-10 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question_marks_studentanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='selected_option',
            new_name='selected_answer',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='marks_obtained',
        ),
        migrations.CreateModel(
            name='StudentTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.studenttest'),
        ),
    ]
