# Generated by Django 5.2.5 on 2025-12-15 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_adminprofile_studentprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='precertificate',
            unique_together={('user', 'course')},
        ),
    ]
