# Generated by Django 5.2.5 on 2025-12-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_selected_option_studentanswer_selected_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='marks_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
