# Generated by Django 5.2.5 on 2025-12-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_studentanswer_marks_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='video_attachments/'),
        ),
    ]
