# Generated by Django 5.2.5 on 2025-12-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_video_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='attachment',
        ),
        migrations.AddField(
            model_name='video',
            name='folder_attachment',
            field=models.FileField(blank=True, null=True, upload_to='video_folders/'),
        ),
    ]
