# Generated by Django 4.2.7 on 2025-12-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_studentprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
