# Generated by Django 4.2.7 on 2025-12-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_certificatesequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentvideoprogress',
            name='updated_at',
        ),
    ]
