# Generated by Django 4.2.7 on 2025-12-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_studentvideoprogress_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking'), ('wallet', 'Wallet'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
