# Generated by Django 4.2.7 on 2025-12-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_enrollment_payment_date_enrollment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='precertificate',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
