# Generated by Django 4.2.7 on 2025-12-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_growwithuslead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
