# Generated by Django 4.2.7 on 2025-12-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_adminprofile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growwithuslead',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='growwithuslead',
            name='full_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='growwithuslead',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
