# Generated by Django 4.2.7 on 2025-12-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemoduleitem',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='coursemoduleitem',
            unique_together={('course', 'order')},
        ),
    ]
