# Generated by Django 5.2.9 on 2025-12-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
