# Generated by Django 5.2.9 on 2025-12-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(max_length=1000),
        ),
    ]
