# Generated by Django 5.2.9 on 2025-12-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_video_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(max_length=1000),
        ),
    ]
