# Generated by Django 5.2.9 on 2026-01-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_video_video_file_alter_video_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source_video',
            field=models.FileField(blank=True, null=True, upload_to='tmp_uploads/'),
        ),
    ]
