# Generated by Django 5.2.9 on 2026-01-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_video_source_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
