# Generated by Django 5.2.9 on 2026-01-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='stage',
            field=models.CharField(default='waiting', max_length=30),
        ),
    ]
