# Generated by Django 5.2.9 on 2026-01-03 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_video_log_video_progress_video_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='log',
        ),
        migrations.RemoveField(
            model_name='video',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='video',
            name='source_video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='stage',
        ),
    ]
