# Generated by Django 5.2.9 on 2026-01-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_video_log_remove_video_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
