# Generated by Django 5.2.9 on 2026-01-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_studentanswer_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='passed',
        ),
        migrations.AddField(
            model_name='studenttest',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
