# Generated by Django 5.2.9 on 2026-01-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_contactus_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='is_contacted',
        ),
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.CharField(choices=[('not', 'Not Contacted'), ('pending', 'Pending'), ('contacted', 'Contacted')], default='not', max_length=10),
        ),
    ]
