# Generated by Django 5.2.9 on 2026-01-07 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=255)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('captured', 'Captured'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
