# Generated by Django 5.2.9 on 2026-01-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_coordinatorcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatorcontact',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='coordinatorcontact',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
