# Generated by Django 5.2.9 on 2026-01-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_coordinatorcontact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatorprofile',
            name='coordinator_id',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
