# Generated by Django 5.2.9 on 2026-01-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_coordinatorprofile_coordinator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingcoordinator',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='pendingcoordinator',
            name='coordinator_id',
            field=models.CharField(default=1, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pendingcoordinator',
            name='photo',
            field=models.ImageField(upload_to='coordinators/passport_photos/'),
        ),
    ]
