# Generated by Django 5.2.9 on 2026-01-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_pendingcoordinator_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingcoordinator',
            name='coordinator_id',
        ),
        migrations.AddField(
            model_name='pendingcoordinator',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
