# Generated by Django 5.2.9 on 2026-01-13 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_coordinatorstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coordinatorprofile'),
        ),
    ]
