# Generated by Django 5.2.9 on 2026-02-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_paymenttransaction_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='resend_count',
            field=models.IntegerField(default=0),
        ),
    ]
