# Generated by Django 5.2.9 on 2026-02-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_passwordresetotp_resend_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatorcontact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='coordinatorcontact',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
