# Generated by Django 5.2.9 on 2026-02-15 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_coordinatorcontact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatorstudent',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='coordinatorstudent',
            unique_together={('coordinator', 'student', 'course')},
        ),
        migrations.CreateModel(
            name='ApprovedCoordinatorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField()),
                ('price_per_student', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_payouts', to='api.coordinatorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField()),
                ('price_per_student', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='api.coordinatorprofile')),
            ],
        ),
        migrations.AddField(
            model_name='coordinatorstudent',
            name='payout_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.coordinatorpayout'),
        ),
        migrations.CreateModel(
            name='PendingCoordinatorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.PositiveIntegerField()),
                ('price_per_student', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_payouts', to='api.coordinatorprofile')),
            ],
        ),
    ]
