# Generated by Django 5.2.9 on 2026-02-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_coordinatorstudent_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingcoordinatorpayout',
            name='coordinator',
        ),
        migrations.DeleteModel(
            name='ApprovedCoordinatorPayout',
        ),
        migrations.DeleteModel(
            name='PendingCoordinatorPayout',
        ),
    ]
