# Generated by Django 5.2.9 on 2026-02-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_pendingcoordinatorpayout_coordinator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemoduleitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
