# Generated by Django 5.2.9 on 2026-02-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_coursemoduleitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='course_name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029')], default='2024', max_length=4),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
