# Generated by Django 5.2.9 on 2026-02-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_studentprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingcoordinator',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
