# Generated by Django 5.2.9 on 2026-02-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_pendingcoordinator_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
