# Generated by Django 5.2.9 on 2026-02-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_coordinatorprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
