# Generated by Django 5.2.9 on 2026-02-25 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_coordinatorprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOPageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_key', models.CharField(max_length=200, unique=True)),
                ('meta_title', models.CharField(max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.URLField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots', models.CharField(default='index,follow', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSEOMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.URLField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots', models.CharField(default='index,follow', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_meta', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='JobSEOMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.CharField(blank=True, max_length=320)),
                ('og_image', models.URLField(blank=True)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots', models.CharField(default='index,follow', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_meta', to='api.job')),
            ],
        ),
    ]
