# Generated by Django 5.2.9 on 2026-02-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_seopagemeta_courseseometa_jobseometa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
