# Generated by Django 5.2.9 on 2026-02-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_delete_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('coordinator', 'Coordinator'), ('seo', 'SEO Manager')], max_length=20),
        ),
    ]
