# Generated by Django 5.2.9 on 2026-02-25 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
